### ISSUE TITLE
Next() is not working when perPage option is larger than the number of slides available

### ISSUE THREAD

**Issue by RenanOliv** [pawelgrzybek/siema#49] opened 2017-04-12 19:40 UTC
#### What is happening
Hi! The carousel drag is becoming unresponsive when you use the `next()` method. This is only happening if the number of slides to be shown is larger than number the slides available. [Here an example with 4 slides and 5 perPage slides](http://codepen.io/RenanOliv/pen/WjNEXB) showing this behaviour.

#### More info that may help
- This seems to affect only `next()`.
- The carousel will work as expected when passing a number with the `goTo()` method.
- `currentSlide` is returning `-1` when `next()` is used.

**Comment by pawelgrzybek** [comment] 2017-04-12 20:02
Hi Renan. Thanks for reporting.

It is a good sport that `next()` method changes value from 0 to `-1`. Is is a bug but not major one as it doesn't affect carousel functionality — it will be fixed though. The issue to resolve here is not inside `next()` method. The problem is with `goTo()` method as it shouldn't slide items in a manner that leaves an empty gaps on the end of a selector — it is bad UX. 

I still consider this as an edge case scenario because a main purpose of using carousel is to slide items when there is not enough of room for it. Nobody is using carousel to waste space on the screen.

Probably the best thing here wold be preventing user from invoking any method like `next()`, `prev()` or `goTo()` when there is no need for them.

It is easy fix and edge case. It will be fixed in next minor release. Thanks 🍻

**Closed** 2017-04-13 12:31 UTC
Labels: bug

**Comment by pawelgrzybek** [comment] 2017-04-13 12:40
Hi @RenanOliv.

Just to let you know that your issue has been resolved. Thanks again for reporting. If you are nosy of the solution, that is the commit...

https://github.com/pawelgrzybek/siema/commit/9fbbe97b17082cb05d01363e01dcabc4c4e3ab2d#diff-0f98adb017f3c5a836cd2a762834f5b9

Thanks a lot and have a great weekend 🍻
