### ISSUE TITLE
Auto play & loop that doesn't reset before each n-th loop

### ISSUE THREAD

**Issue by joshRpowell** [pawelgrzybek/siema#129] opened 2018-01-29 20:09 UTC
Using a modified Auto play & loop from [codepen](https://codepen.io/pawelgrzybek/pen/MbPbLM)

http://recordit.co/zwZuyR4bwl

```js
import Siema from "siema";

const siemaSelector = "carousel-subtitle";
if (document.getElementsByClassName(siemaSelector).length) {
  const carouselSubtitle = new Siema({
    selector: `.${siemaSelector}`,
    duration: 1000,
    loop: true
  });

  setInterval(() => carouselSubtitle.next(), 4000);
}
```

Is there a way to config that goes from slide `1 to 2 to 3 to 1` without passing over 2 on the reset?

**Comment by pawelgrzybek** [comment] 2018-01-30 07:45
Hi.

At this moment this features is not possible. It is a duplicate of #93 where user requested the same functionality. I'm planing to release it in upcoming version 1.5.

Stay tuned and have a great day 😊

**Closed by pawelgrzybek** 2018-01-30 07:45 UTC
